<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="PureBook-S14" failures="0" tests="4" name="example.TimeoutException" time="1.022" errors="1" timestamp="2023-08-11T21:47:43 IST" skipped="1">
  <testcase classname="example.TimeoutException" name="tc2" time="0.001"/>
  <testcase classname="example.TimeoutException" name="tc4" time="0.000">
    <skipped/>
  </testcase> <!-- tc4 -->
  <testcase classname="example.TimeoutException" name="tc1" time="0.002"/>
  <testcase classname="example.TimeoutException" name="tc3" time="1.019">
    <error message="Method example.TimeoutException.tc3() didn&#039;t finish within the time-out 1000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method example.TimeoutException.tc3() didn't finish within the time-out 1000
at java.base@17.0.7/java.lang.Thread.sleep(Native Method)
at app//example.TimeoutException.tc3(TimeoutException.java:21)
at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base@17.0.7/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base@17.0.7/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base@17.0.7/java.lang.reflect.Method.invoke(Method.java:568)
at app//org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at app//org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at app//org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base@17.0.7/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base@17.0.7/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base@17.0.7/java.lang.Thread.run(Thread.java:833)
]]>
    </error>
  </testcase> <!-- tc3 -->
</testsuite> <!-- example.TimeoutException -->
